In [ ]:
# nomer 5
import numpy as np

# Definisi matriks A, B, C, dan D
A = np.array([[-1, 0, 1],
              [-1, 1, 2],
              [ 1, 0, 1]])

B = np.array([[4, 0, 2],
              [1, 2, 3],
              [-2, 1, 0]])

C = np.array([[2, 2, -1, -4],
              [2, 3, -2, -7],
              [1, 1, -3, -6],
              [2, 2, -3, -7]])

D = np.array ([[2, -1, 1, -1],
               [-5, 1, -6, 7],
               [5, 0, 6, -8],
               [-3, 0, -4, 5]])

# Menghitung invers dari AB dan CD
AB_inv = np.linalg.inv(A.dot(B))
CD_inv = np.linalg.inv(C.dot(D))

# Menghitung AB^(-1)(BA)
result1 = np.linalg.inv(A.dot(B)).dot(B.dot(A))

# Menghitung CD^(-1)(D^(-1)C)
result2 = np.linalg.inv(C.dot(D)).dot(D.dot(np.linalg.inv(D).dot(C)))

print("AB^(-1):")
print(AB_inv)
print("\nCD^(-1):")
print(CD_inv)
print("\n(AB)^(-1)(BA):")
print(result1)
print("\n(CD)^(-1)(D^(-1)C):")
print(result2)


AB^(-1):
[[ 1.75 -1.    2.25]
 [ 4.   -2.    5.  ]
 [-3.75  2.   -4.25]]

CD^(-1):
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

(AB)^(-1)(BA):
[[-1.25  0.25  2.5 ]
 [-3.    1.    8.  ]
 [ 3.25 -0.25 -6.5 ]]

(CD)^(-1)(D^(-1)C):
[[ 2.  2. -1. -4.]
 [ 2.  3. -2. -7.]
 [ 1.  1. -3. -6.]
 [ 2.  2. -3. -7.]]


In [ ]:
# nomer 6
import numpy as np
A= np.array ([[1, 3, 5, 7],
              [2, 4, 6, 8],
              [-3, -2, -1, 0]])
u= np.array ([[10, 20, 30]])
# a. Cetak matriks A, vector u, ukuran matriks, dan ukuran vector
print("Matriks A:")
print(A)
print("\nVector u:")
print(u)
print("\nUkuran matriks A:", A.shape)
print("Ukuran vector u:", u.shape)

# b. Cetak kolom pertama dari matriks A
print("\nKolom pertama dari matriks A:")
print(A[:, 0])

# c. Cetak dua baris pertama dari matriks A
print("\nDua baris pertama dari matriks A:")
print(A[:2, :])

# d. Cetak dua entri pertama dari vector u
print("\nDua entri pertama dari vector u:")
print(u[:2])

# e. Cetak dua entri terakhir dari vector u
print("\nDua entri terakhir dari vector u:")
print(u[-2:])

# f. Cetak kiri bawah 2x2 dari matriks A
print("\nKiri bawah 2x2 dari matriks A:")
print(A[1:, :-1])

# g. Cetak dua elemen tengah dari baris tengah matriks A
print("\nDua elemen tengah dari baris tengah matriks A:")
print(A[1, 1:3])

Matriks A:
[[ 1  3  5  7]
 [ 2  4  6  8]
 [-3 -2 -1  0]]

Vector u:
[[10 20 30]]

Ukuran matriks A: (3, 4)
Ukuran vector u: (1, 3)

Kolom pertama dari matriks A:
[ 1  2 -3]

Dua baris pertama dari matriks A:
[[1 3 5 7]
 [2 4 6 8]]

Dua entri pertama dari vector u:
[[10 20 30]]

Dua entri terakhir dari vector u:
[[10 20 30]]

Kiri bawah 2x2 dari matriks A:
[[ 2  4  6]
 [-3 -2 -1]]

Dua elemen tengah dari baris tengah matriks A:
[4 6]


In [ ]:
# nomer 8
import numpy as np

# Definisi matriks A, B, C, dan D
A = np.array([[-1, 0, 1],
              [-1, 1, 2],
              [ 1, 0, 1]])

B = np.array([[4, 0, 2],
              [1, 2, 3],
              [-2, 1, 0]])

C = np.array([[2, 2, -1, -4],
              [2, 3, -2, -7],
              [1, 1, -3, -6],
              [2, 2, -3, -7]])

D = np.array ([[2, -1, 1, -1],
               [-5, 1, -6, 7],
               [5, 0, 6, -8],
               [-3, 0, -4, 5]])
# Membuat matriks diagonal
matriks_diagonal = np.diag([1, 2, 3])

# Menampilkan matriks diagonal
print("Matriks diagonal:")
print(matriks_diagonal)

# Menghitung determinan dari matriks diagonal
determinan = np.linalg.det(matriks_diagonal)

# Menampilkan determinan
print("\nDeterminan dari matriks diagonal:", determinan)

Matriks diagonal:
[[1 0 0]
 [0 2 0]
 [0 0 3]]

Determinan dari matriks diagonal: 6.0


In [ ]:
# nomer 3
import numpy as np
# Matriks koefisien A
A = np.array([[3, -1, 2],
               [-4, 2, 7],
               [11, 5, 9]])

# Vektor hasil B
B = np.array([11, 13, 28])
A_inv = np.linalg.inv(A)
# Menyelesaikan sistem persamaan linear
X1 = np.dot(A_inv,B)

# Menampilkan solusi
print("Solusi dari sistem persamaan linear:")
print(X1)

# Menghitung nilai x + 7y - 2z
x, y, z = X1
result = x + 7*y - 2*z

# Menampilkan hasil nilai x + 7y - 2z
print(f"Nilai dari x + 7y - 2z adalah: {result}")